name: Image release

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        UBI_VERSION: [7,8]
        include:
        - UBI_VERSION: 7
          UBI_VERSION_MINOR: 9
        - UBI_VERSION: 8
          UBI_VERSION_MINOR: 3
        OPENJDK_VERSION: [8,11]
        IMAGE: ['jdk','jre','jre-headless']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASS }}

      - name: Build and push OpenJDK images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./ubi-openjdk-${{ matrix.IMAGE }}.Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          build-args: |
            UBI_VERSION=${{ matrix.UBI_VERSION }}
            UBI_VERSION_MINOR=${{ matrix.UBI_VERSION_MINOR }}
            OPENJDK_VERSION=${{ matrix.OPENJDK_VERSION }}
          push: true
          tags: |
            quay.io/rhmessagingqe/ubi${{ matrix.UBI_VERSION }}-openjdk-${{ matrix.IMAGE }}:${{ matrix.OPENJDK_VERSION }}
